1-5 tasks from 1-st module
js-tasks-ru/jsbasic-20240115_gergesova pull request #2
Opened 2024-01-23 20:05 UTC by Yuliia-Kosterina

Решения на проверку по 5 задачам из первого модуля.

2024-01-23 20:05 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-01-24 17:31 UTC, SinimaWath requested changes

2024-01-24 17:31 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
`return str.toLowerCase().includes(str1) || str.toLowerCase().includes(str2)` - если результат операции boolean, то в этом сценарии не нужен if

2024-01-24 17:31 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
`return Boolean(name) && !name.includes(' ') && (name.length >= 4)` - если результат операции boolean, то в этом сценарии не нужен if

2024-01-24 19:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-01-27 14:38 UTC, SinimaWath approved these changes

2024-01-27 14:38 UTC, merged