1-5 tasks from the third module
js-tasks-ru/jsbasic-20240115_gergesova pull request #4
Opened 2024-02-03 11:04 UTC by Yuliia-Kosterina

2024-02-03 11:04 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-03 17:44 UTC, SinimaWath requested changes

2024-02-03 17:44 UTC, SinimaWath commented on 3-module/1-task/index.js
> +let users = [vasya, petya, masha];
Этот лишний код надо убрать

2024-02-03 17:44 UTC, SinimaWath commented on 3-module/2-task/index.js
> +let arr = [5, 3, 8, 1];
Этот лишний код надо убрать

2024-02-03 17:44 UTC, SinimaWath commented on 3-module/2-task/index.js
> +console.log(arr); // [5,3,8,1] (без изменений)
Этот лишний код надо убрать

2024-02-03 17:44 UTC, SinimaWath commented on 3-module/1-task/index.js
> +let names = namify(users); // ['Вася', 'Петя', 'Маша']
Этот лишний код надо убрать

2024-02-03 18:45 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-02-05 14:05 UTC, SinimaWath approved these changes

2024-02-05 14:06 UTC, merged